In [1]:
#Get 5 Year's Worth of Stock Price Data via API
import os
import pandas as pd
import alpaca_trade_api as tradeapi
import numpy as np
from dotenv import load_dotenv
load_dotenv()
%matplotlib inline
from alpaca_trade_api.rest import REST, TimeFrame, TimeFrameUnit

In [2]:
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="vs2"
)

ticker = ['ICF']
timeframe = '1Day'
start_date = pd.Timestamp("2017-05-01", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2023-04-01", tz="America/New_York").isoformat()

df_ticker = alpaca.get_bars(
    ticker,
    timeframe,
    start=start_date,
    end=end_date
).df

ICF = df_ticker[df_ticker['symbol']== 'ICF'].drop('symbol', axis=1)
icf_closing_prices = pd.DataFrame()
icf_closing_prices['ICF'] = ICF['close']

## Create A Long-Position Algorithm

In [3]:
# Calculate the daily returns using the closing prices and the pct_change function
icf_closing_prices['Actual Returns'] = icf_closing_prices['ICF'].pct_change()

# Drop all NaN values from the DataFrame
icf_closing_prices = icf_closing_prices.dropna()

# Review the DataFrame
display(icf_closing_prices.head())
display(icf_closing_prices.tail())

                              ICF  Actual Returns
timestamp
2017-05-02 04:00:00+00:00  100.34        0.000598
2017-05-03 04:00:00+00:00   99.05       -0.012856
2017-05-04 04:00:00+00:00   99.08        0.000303
2017-05-05 04:00:00+00:00   99.74        0.006661
2017-05-08 04:00:00+00:00   99.21       -0.005314

                             ICF  Actual Returns
timestamp
2023-03-27 04:00:00+00:00  52.49       -0.002660
2023-03-28 04:00:00+00:00  52.39       -0.001905
2023-03-29 04:00:00+00:00  53.61        0.023287
2023-03-30 04:00:00+00:00  54.28        0.012498
2023-03-31 04:00:00+00:00  55.54        0.023213

In [4]:
# Create the short_window and long_window variables

short_window = 50
long_window = 75

# Using Close Columns and Rolling & Mean Functions and Create the SMA columns for the moving average

icf_closing_prices['SMA Short'] = icf_closing_prices['ICF'].rolling(window=short_window).mean()
icf_closing_prices['SMA Long'] = icf_closing_prices['ICF'].rolling(window=long_window).mean()

# Review the DataFrame

icf_closing_prices.tail()

                             ICF  Actual Returns  SMA Short  SMA Long
timestamp
2023-03-27 04:00:00+00:00  52.49       -0.002660    57.1836   56.7416
2023-03-28 04:00:00+00:00  52.39       -0.001905    57.0618   56.6880
2023-03-29 04:00:00+00:00  53.61        0.023287    56.9618   56.6456
2023-03-30 04:00:00+00:00  54.28        0.012498    56.8946   56.6136
2023-03-31 04:00:00+00:00  55.54        0.023213    56.8568   56.5924

In [5]:
icf_closing_prices['Signal'] = 0.0

In [6]:
# Create the features set
# Assign a copy of the SMA Short and SMA Long columns to a new DataFrame called X
X = icf_closing_prices[['SMA Short', 'SMA Long']].shift().dropna().copy()

# Display sample data
display(X.head())
display(X.tail())

                           SMA Short    SMA Long
timestamp
2017-08-17 04:00:00+00:00   101.4810  100.935600
2017-08-18 04:00:00+00:00   101.4786  100.942133
2017-08-21 04:00:00+00:00   101.4598  100.951733
2017-08-22 04:00:00+00:00   101.4574  100.977067
2017-08-23 04:00:00+00:00   101.4316  100.988933

                           SMA Short   SMA Long
timestamp
2023-03-27 04:00:00+00:00    57.3118  56.791733
2023-03-28 04:00:00+00:00    57.1836  56.741600
2023-03-29 04:00:00+00:00    57.0618  56.688000
2023-03-30 04:00:00+00:00    56.9618  56.645600
2023-03-31 04:00:00+00:00    56.8946  56.613600

In [7]:
# Create target set
# Create a new column in the icf_closing_prices DataFrame called singal settings its value to zero
icf_closing_prices["Signal"] = 0.0
icf_closing_prices

                              ICF  Actual Returns  SMA Short  SMA Long  Signal
timestamp
2017-05-02 04:00:00+00:00  100.34        0.000598        NaN       NaN     0.0
2017-05-03 04:00:00+00:00   99.05       -0.012856        NaN       NaN     0.0
2017-05-04 04:00:00+00:00   99.08        0.000303        NaN       NaN     0.0
2017-05-05 04:00:00+00:00   99.74        0.006661        NaN       NaN     0.0
2017-05-08 04:00:00+00:00   99.21       -0.005314        NaN       NaN     0.0
...                           ...             ...        ...       ...     ...
2023-03-27 04:00:00+00:00   52.49       -0.002660    57.1836   56.7416     0.0
2023-03-28 04:00:00+00:00   52.39       -0.001905    57.0618   56.6880     0.0
2023-03-29 04:00:00+00:00   53.61        0.023287    56.9618   56.6456     0.0
2023-03-30 04:00:00+00:00   54.28        0.012498    56.8946   56.6136     0.0
2023-03-31 04:00:00+00:00   55.54        0.023213    56.8568   56.5924     0.0

[1490 rows x 5 columns]

In [44]:
# # Create the signal to buy
icf_closing_prices.loc[(icf_closing_prices["Actual Returns"] >=0), "Signal"] = 1

# # Create the signal to sell
icf_closing_prices.loc[(icf_closing_prices["Actual Returns"] < 0), "Signal"] = -1

# Copy the new signal column to a new Series called y
y = icf_closing_prices["Signal"].copy()
pd.set_option('display.max_rows', 500)
y.tail()

timestamp
2023-03-27 04:00:00+00:00   -1.0
2023-03-28 04:00:00+00:00   -1.0
2023-03-29 04:00:00+00:00    1.0
2023-03-30 04:00:00+00:00    1.0
2023-03-31 04:00:00+00:00    1.0
Name: Signal, dtype: float64

## Split the Data Into Training & Testing Datasets

### Creating the Training Datasets

In [11]:
# Imports
from sklearn.preprocessing import StandardScaler
from pandas.tseries.offsets import DateOffset

In [12]:
# Select the start of the training period
training_begin = X.index.min()

# Display the training begin date
print(training_begin)

2017-08-17 04:00:00+00:00

In [13]:
# Select the ending period for the training data with an offset of "" months
training_end = X.index.min() + DateOffset(months=15)

# Display the training end date
print(training_end)

2018-11-17 04:00:00+00:00

In [14]:
# Generate the X_train and y_train DataFrames
X_train = X.loc[training_begin:training_end]
y_train = y.loc[training_begin:training_end]

# Display sample data
X_train.head()

                           SMA Short    SMA Long
timestamp
2017-08-17 04:00:00+00:00   101.4810  100.935600
2017-08-18 04:00:00+00:00   101.4786  100.942133
2017-08-21 04:00:00+00:00   101.4598  100.951733
2017-08-22 04:00:00+00:00   101.4574  100.977067
2017-08-23 04:00:00+00:00   101.4316  100.988933

### Creating the Testing Datasets

In [15]:
# Generate the X_test and y_test DataFrames
X_test = X.loc[training_end:]
y_test = y.loc[training_end:]

# Display sample data
X_test.head()

                           SMA Short    SMA Long
timestamp
2018-11-19 05:00:00+00:00    99.7761  100.692733
2018-11-20 05:00:00+00:00    99.7759  100.699933
2018-11-21 05:00:00+00:00    99.7571  100.695000
2018-11-23 05:00:00+00:00    99.7351  100.692200
2018-11-26 05:00:00+00:00    99.6973  100.691533

### Standardizing the Data

In [16]:
# Create a StandardScaler instance
scaler = StandardScaler()
 
# Apply the scaler model to fit the X-train data
X_scaler = scaler.fit(X_train)
 
# Transform the X_train and X_test DataFrames using the X_scaler
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Introduce the Machine Learning Model: Logistic Regression

In [17]:
# Import LogisticRegression from sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [18]:
# Create an instance of the LogisticRegression model
logistic_regression_model = LogisticRegression()

In [19]:
# Fit the LogisticRegression model
logistic_regression_model.fit(X_train_scaled, y_train)

LogisticRegression()

In [20]:
# Use the trained LogisticRegression model to predict the trading signals for the training data
lr_training_signal_predictions = logistic_regression_model.predict(X_train_scaled)

# Display the predictions
lr_training_signal_predictions

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.])

In [21]:
# Generate a classification report using the training data and the logistic regression model's predications
lr_training_report = classification_report(y_train, lr_training_signal_predictions)

# Review the classification report
print(lr_training_report)

              precision    recall  f1-score   support

        -1.0       0.52      0.29      0.37       147
         1.0       0.56      0.76      0.64       170

    accuracy                           0.55       317
   macro avg       0.54      0.53      0.51       317
weighted avg       0.54      0.55      0.52       317

## Backtest the Logistic Regression Model

In [22]:
# Use the trained model to predict the trading signals for the testing data.
lr_testing_signal_predictions = logistic_regression_model.predict(X_test_scaled)

In [23]:
# Generate a classification report using the testing data and the logistic regression model's predictions
lr_testing_report = classification_report(y_test, lr_testing_signal_predictions)

# Review the testing classification report
print(lr_testing_report)

              precision    recall  f1-score   support

        -1.0       0.49      0.56      0.52       505
         1.0       0.58      0.51      0.54       593

    accuracy                           0.53      1098
   macro avg       0.53      0.53      0.53      1098
weighted avg       0.54      0.53      0.53      1098

In [24]:
# Create a new empty predictions DataFrame using code provided below.
predictions_df = pd.DataFrame(index=X_test.index)
predictions_df["Predicted Signal"] = lr_testing_signal_predictions
predictions_df["Actual Returns"] = icf_closing_prices["Actual Returns"]
predictions_df["Trading Algorithm Returns"] = predictions_df["Actual Returns"] * predictions_df["Predicted Signal"]
predictions_df.tail()

,Predicted Signal,Actual Returns,Trading Algorithm Returns
timestamp,,,
2023-03-27 04:00:00+00:00,-1.0,-0.002660,0.002660
2023-03-28 04:00:00+00:00,-1.0,-0.001905,0.001905
2023-03-29 04:00:00+00:00,-1.0,0.023287,-0.023287
2023-03-30 04:00:00+00:00,-1.0,0.012498,-0.012498
2023-03-31 04:00:00+00:00,-1.0,0.023213,-0.023213

In [25]:
#Calcualte the cumulative returns for the actual returns and trading algorithm returns
cumulative_df = pd.DataFrame(index=X_test.index)
cumulative_df['Actual Cumulative Returns'] = (1 + predictions_df[['Actual Returns']]).cumprod()
cumulative_df['Algo Cumulative Returns'] = (1 + predictions_df[['Trading Algorithm Returns']]).cumprod()

#Review the cumulative returns dataframe
cumulative_df.tail(50)

                           Actual Cumulative Returns  Algo Cumulative Returns
timestamp
2023-01-20 05:00:00+00:00                   0.566433                 0.528325
2023-01-23 05:00:00+00:00                   0.567115                 0.527689
2023-01-24 05:00:00+00:00                   0.570037                 0.524970
2023-01-25 05:00:00+00:00                   0.569745                 0.525239
2023-01-26 05:00:00+00:00                   0.575687                 0.519761
2023-01-27 05:00:00+00:00                   0.580947                 0.515012
2023-01-30 05:00:00+00:00                   0.573739                 0.521402
2023-01-31 05:00:00+00:00                   0.585720                 0.510514
2023-02-01 05:00:00+00:00                   0.589616                 0.507118
2023-02-02 05:00:00+00:00                   0.603059                 0.495556
2023-02-03 05:00:00+00:00                   0.590980                 0.505482
2023-02-06 05:00:00+00:00                   0.587376                 0.508565
2023-02-07 05:00:00+00:00                   0.585233                 0.510420
2023-02-08 05:00:00+00:00                   0.584064                 0.511440
2023-02-09 05:00:00+00:00                   0.577732                 0.516984
2023-02-10 05:00:00+00:00                   0.579291                 0.515589
2023-02-13 05:00:00+00:00                   0.583869                 0.511514
2023-02-14 05:00:00+00:00                   0.578414                 0.516293
2023-02-15 05:00:00+00:00                   0.579973                 0.514902
2023-02-16 05:00:00+00:00                   0.575102                 0.519226
2023-02-17 05:00:00+00:00                   0.572764                 0.521337
2023-02-21 05:00:00+00:00                   0.561952                 0.531178
2023-02-22 05:00:00+00:00                   0.556497                 0.536335
2023-02-23 05:00:00+00:00                   0.560296                 0.532673
2023-02-24 05:00:00+00:00                   0.550750                 0.541749
2023-02-27 05:00:00+00:00                   0.551432                 0.541078
2023-02-28 05:00:00+00:00                   0.550166                 0.542321
2023-03-01 05:00:00+00:00                   0.541691                 0.550674
2023-03-02 05:00:00+00:00                   0.548510                 0.543743
2023-03-03 05:00:00+00:00                   0.557763                 0.534569
2023-03-06 05:00:00+00:00                   0.555913                 0.536343
2023-03-07 05:00:00+00:00                   0.542275                 0.549500
2023-03-08 05:00:00+00:00                   0.549386                 0.542295
2023-03-09 05:00:00+00:00                   0.537405                 0.554121
2023-03-10 05:00:00+00:00                   0.518703                 0.573405
2023-03-13 04:00:00+00:00                   0.528638                 0.562422
2023-03-14 04:00:00+00:00                   0.533996                 0.556722
2023-03-15 04:00:00+00:00                   0.534775                 0.555910
2023-03-16 04:00:00+00:00                   0.533119                 0.557631
2023-03-17 04:00:00+00:00                   0.521917                 0.569348
2023-03-20 04:00:00+00:00                   0.526885                 0.563929
2023-03-21 04:00:00+00:00                   0.523476                 0.567578
2023-03-22 04:00:00+00:00                   0.504286                 0.588384
2023-03-23 04:00:00+00:00                   0.498831                 0.594749
2023-03-24 04:00:00+00:00                   0.512663                 0.578257
2023-03-27 04:00:00+00:00                   0.511299                 0.579795
2023-03-28 04:00:00+00:00                   0.510325                 0.580900
2023-03-29 04:00:00+00:00                   0.522209                 0.567372
2023-03-30 04:00:00+00:00                   0.528736                 0.560281
2023-03-31 04:00:00+00:00                   0.541009                 0.547276

## Back Test the Actual Trading Strategy

In [35]:
#Create the dataframe for the Actual Cumualtive Returns
algo_backtest = pd.concat([icf_closing_prices, cumulative_df], axis='columns', join='inner')

#Drop the Algo Cumulative Returns Column
algo_backtest.drop(columns='Actual Cumulative Returns', inplace=True)

# Calculate the points in time at which a position should be taken, 1 or -1
algo_backtest['Entry/Exit'] = algo_backtest['Signal'].diff()
pd.set_option('display.max_rows', None)

#Review the dataframe
algo_backtest.head(100)

,ICF,Actual Returns,SMA Short,SMA Long,Signal,Algo Cumulative Returns,Entry/Exit
timestamp,,,,,,,
2018-11-19 05:00:00+00:00,102.99,0.003214,99.7759,100.699933,1.0,1.003214,NaN
2018-11-20 05:00:00+00:00,102.02,-0.009418,99.7571,100.695000,-1.0,0.993766,-2.0
2018-11-21 05:00:00+00:00,101.93,-0.000882,99.7351,100.692200,-1.0,0.992889,0.0
2018-11-23 05:00:00+00:00,101.64,-0.002845,99.6973,100.691533,-1.0,0.990064,0.0
2018-11-26 05:00:00+00:00,101.75,0.001082,99.6767,100.693400,1.0,0.991136,2.0
2018-11-27 05:00:00+00:00,102.25,0.004914,99.6555,100.714733,1.0,0.996006,0.0
2018-11-28 05:00:00+00:00,103.04,0.007726,99.6619,100.745800,1.0,1.003702,0.0
2018-11-29 05:00:00+00:00,103.19,0.001456,99.6947,100.775133,1.0,1.005163,0.0
2018-11-30 05:00:00+00:00,104.07,0.008528,99.7285,100.803133,1.0,1.013735,0.0
2018-12-03 05:00:00+00:00,104.84,0.007399,99.7763,100.830200,1.0,1.021235,0.0
2018-12-04 05:00:00+00:00,103.41,-0.013640,99.8393,100.824600,-1.0,1.007306,-2.0
2018-12-06 05:00:00+00:00,106.05,0.025529,99.9549,100.854867,1.0,1.033022,2.0
2018-12-07 05:00:00+00:00,104.78,-0.011975,100.0849,100.880200,-1.0,1.020651,-2.0
2018-12-10 05:00:00+00:00,104.09,-0.006585,100.1929,100.905667,-1.0,1.013929,0.0
2018-12-11 05:00:00+00:00,104.25,0.001537,100.2763,100.935800,1.0,1.015488,2.0
2018-12-12 05:00:00+00:00,102.08,-0.020815,100.3321,100.928467,-1.0,0.994350,-2.0
2018-12-13 05:00:00+00:00,102.68,0.005878,100.4037,100.931000,1.0,1.000195,2.0
2018-12-14 05:00:00+00:00,102.53,-0.001461,100.4905,100.914867,-1.0,0.998734,-2.0
2018-12-17 05:00:00+00:00,98.19,-0.042329,100.5027,100.842467,-1.0,0.956458,0.0
2018-12-18 05:00:00+00:00,99.20,0.010286,100.5343,100.789933,1.0,0.966297,2.0
2018-12-19 05:00:00+00:00,98.31,-0.008972,100.5225,100.720200,-1.0,0.957627,-2.0
2018-12-20 05:00:00+00:00,97.06,-0.012715,100.4777,100.647000,-1.0,0.945451,0.0
2018-12-21 05:00:00+00:00,95.91,-0.011848,100.4363,100.548333,-1.0,0.934249,0.0
2018-12-24 05:00:00+00:00,92.00,-0.040767,100.3729,100.393133,-1.0,0.896162,0.0
2018-12-26 05:00:00+00:00,94.87,0.031196,100.3677,100.292467,1.0,0.924118,2.0
2018-12-27 05:00:00+00:00,95.13,0.002741,100.3581,100.187533,1.0,0.926651,0.0
2018-12-28 05:00:00+00:00,95.41,0.002943,100.3169,100.086867,1.0,0.929379,0.0
2018-12-31 05:00:00+00:00,95.70,0.003040,100.2863,99.989133,1.0,0.932203,0.0
2019-01-02 05:00:00+00:00,93.31,-0.024974,100.2069,99.852867,-1.0,0.908923,-2.0
2019-01-03 05:00:00+00:00,93.69,0.004072,100.1185,99.731667,1.0,0.912624,2.0
2019-01-04 05:00:00+00:00,94.54,0.009072,100.0744,99.614733,1.0,0.920904,0.0
2019-01-07 05:00:00+00:00,95.22,0.007193,100.0312,99.514733,1.0,0.927528,0.0
2019-01-08 05:00:00+00:00,97.14,0.020164,99.9992,99.455933,1.0,0.946230,0.0
2019-01-09 05:00:00+00:00,96.92,-0.002265,99.9414,99.383133,-1.0,0.944087,-2.0
2019-01-10 05:00:00+00:00,98.57,0.017024,99.9626,99.331400,1.0,0.960160,2.0
2019-01-11 05:00:00+00:00,98.78,0.002130,99.9606,99.311667,1.0,0.962205,0.0
2019-01-14 05:00:00+00:00,98.50,-0.002835,99.9294,99.288067,-1.0,0.959478,-2.0
2019-01-15 05:00:00+00:00,99.64,0.011574,99.9500,99.306200,1.0,0.970583,2.0
2019-01-16 05:00:00+00:00,100.22,0.005821,99.9764,99.326600,1.0,0.976232,0.0
2019-01-17 05:00:00+00:00,100.53,0.003093,100.0302,99.332600,1.0,0.979252,0.0
2019-01-18 05:00:00+00:00,100.88,0.003482,100.0570,99.353800,1.0,0.982661,0.0
2019-01-22 05:00:00+00:00,100.67,-0.002082,100.0676,99.374733,-1.0,0.980616,-2.0
2019-01-23 05:00:00+00:00,100.60,-0.000695,100.0522,99.406867,-1.0,0.979934,0.0
2019-01-24 05:00:00+00:00,100.74,0.001392,100.0364,99.449000,1.0,0.981297,2.0
2019-01-25 05:00:00+00:00,101.88,0.011316,100.0386,99.505800,1.0,0.992402,0.0
2019-01-28 05:00:00+00:00,103.04,0.011386,100.0574,99.561000,1.0,1.003702,0.0
2019-01-29 05:00:00+00:00,103.97,0.009026,100.0908,99.623267,1.0,1.012761,0.0
2019-01-30 05:00:00+00:00,104.85,0.008464,100.1418,99.714867,1.0,1.021333,0.0
2019-01-31 05:00:00+00:00,105.86,0.009633,100.2316,99.857400,1.0,1.031171,0.0
2019-02-01 05:00:00+00:00,105.10,-0.007179,100.2804,99.990333,-1.0,1.023768,-2.0
2019-02-04 05:00:00+00:00,105.97,0.008278,100.3400,100.128467,1.0,1.032242,2.0
2019-02-05 05:00:00+00:00,106.59,0.005851,100.4314,100.250067,1.0,1.038282,0.0
2019-02-06 05:00:00+00:00,105.87,-0.006755,100.5102,100.365267,-1.0,1.031268,-2.0
2019-02-07 05:00:00+00:00,106.87,0.009446,100.6148,100.493133,1.0,1.041009,2.0
2019-02-08 05:00:00+00:00,107.00,0.001216,100.7198,100.611667,1.0,1.042275,0.0
2019-02-11 05:00:00+00:00,107.27,0.002523,100.8202,100.752000,1.0,1.044906,0.0
2019-02-12 05:00:00+00:00,106.39,-0.008204,100.8872,100.872133,-1.0,1.036334,-2.0
2019-02-13 05:00:00+00:00,107.03,0.006016,100.9640,100.982667,1.0,1.042568,2.0
2019-02-14 05:00:00+00:00,107.61,0.005419,101.0348,101.086667,1.0,1.048217,0.0
2019-02-15 05:00:00+00:00,108.14,0.004925,101.1008,101.228400,1.0,1.053380,0.0
2019-02-19 05:00:00+00:00,108.31,0.001572,101.1988,101.354133,1.0,1.055036,0.0
2019-02-20 05:00:00+00:00,107.44,-0.008032,101.2266,101.452533,-1.0,1.046561,-2.0
2019-02-21 05:00:00+00:00,107.72,0.002606,101.2854,101.574000,1.0,1.049289,2.0
2019-02-22 05:00:00+00:00,108.41,0.006405,101.3718,101.700800,1.0,1.056010,0.0
2019-02-25 05:00:00+00:00,107.60,-0.007472,101.4388,101.830933,-1.0,1.048120,-2.0
2019-02-26 05:00:00+00:00,107.46,-0.001301,101.5464,101.936533,-1.0,1.046756,0.0
2019-02-27 05:00:00+00:00,106.92,-0.005025,101.6312,102.026933,-1.0,1.041496,0.0
2019-02-28 05:00:00+00:00,107.38,0.004302,101.7282,102.107067,1.0,1.045977,2.0
2019-03-01 05:00:00+00:00,107.14,-0.002235,101.9072,102.181867,-1.0,1.043639,-2.0
2019-03-04 05:00:00+00:00,107.61,0.004387,102.0754,102.259733,1.0,1.048217,2.0
2019-03-05 05:00:00+00:00,108.01,0.003717,102.2694,102.338533,1.0,1.052114,0.0
2019-03-06 05:00:00+00:00,107.59,-0.003889,102.4800,102.409067,-1.0,1.048023,-2.0
2019-03-07 05:00:00+00:00,107.43,-0.001487,102.7104,102.477467,-1.0,1.046464,0.0
2019-03-08 05:00:00+00:00,107.54,0.001024,103.0212,102.559733,1.0,1.047536,2.0
2019-03-11 04:00:00+00:00,109.07,0.014227,103.3052,102.645200,1.0,1.062439,0.0
2019-03-12 04:00:00+00:00,109.70,0.005776,103.5966,102.734667,1.0,1.068576,0.0
2019-03-13 04:00:00+00:00,110.18,0.004376,103.8920,102.843467,1.0,1.073252,0.0
2019-03-14 04:00:00+00:00,110.47,0.002632,104.1874,102.957333,1.0,1.076076,0.0
2019-03-15 04:00:00+00:00,109.86,-0.005522,104.5184,103.066933,-1.0,1.070134,-2.0
2019-03-18 04:00:00+00:00,109.17,-0.006281,104.8280,103.165867,-1.0,1.063413,0.0
2019-03-19 04:00:00+00:00,108.73,-0.004030,105.1118,103.252267,-1.0,1.059127,0.0
2019-03-20 04:00:00+00:00,108.55,-0.001655,105.3784,103.325733,-1.0,1.057374,0.0
2019-03-21 04:00:00+00:00,110.50,0.017964,105.6456,103.423200,1.0,1.076369,2.0
2019-03-22 04:00:00+00:00,110.12,-0.003439,105.9096,103.503867,-1.0,1.072667,-2.0
2019-03-25 04:00:00+00:00,110.20,0.000726,106.1422,103.575333,1.0,1.073446,2.0
2019-03-26 04:00:00+00:00,111.01,0.007350,106.3868,103.676667,1.0,1.065556,0.0
2019-03-27 04:00:00+00:00,110.56,-0.004054,106.6280,103.736800,-1.0,1.069876,-2.0
2019-03-28 04:00:00+00:00,111.49,0.008412,106.8650,103.826267,1.0,1.060876,2.0
2019-03-29 04:00:00+00:00,111.20,-0.002601,107.0846,103.921067,-1.0,1.063636,-2.0
2019-04-01 04:00:00+00:00,111.08,-0.001079,107.2956,104.012133,-1.0,1.064783,0.0
2019-04-02 04:00:00+00:00,112.04,0.008642,107.5188,104.144933,1.0,1.055581,2.0
2019-04-03 04:00:00+00:00,111.79,-0.002231,107.7412,104.266400,-1.0,1.057936,-2.0
2019-04-04 04:00:00+00:00,111.50,-0.002594,107.9592,104.386000,-1.0,1.060681,0.0
2019-04-05 04:00:00+00:00,112.23,0.006547,108.1890,104.573200,1.0,1.053737,2.0
2019-04-08 04:00:00+00:00,111.64,-0.005257,108.3842,104.739067,-1.0,1.059276,-2.0
2019-04-09 04:00:00+00:00,111.11,-0.004747,108.5456,104.909733,-1.0,1.064305,0.0
2019-04-10 04:00:00+00:00,112.07,0.008640,108.7076,105.109867,1.0,1.055109,2.0
2019-04-11 04:00:00+00:00,111.98,-0.000803,108.8502,105.324133,-1.0,1.055957,-2.0
2019-04-12 04:00:00+00:00,112.60,0.005537,108.9850,105.598800,1.0,1.050110,2.0
2019-04-15 04:00:00+00:00,112.07,-0.004707,109.1244,105.828133,-1.0,1.055053,-2.0

In [36]:
# Set the intial capital 
initial_capital = float(100000)

# Set the share size
share_size = 500

#Take the share position where the dual moving average crossover is 1
algo_backtest['Position'] = share_size * algo_backtest['Signal']

# Find the points in time where a 500 share position is bought or sold
algo_backtest["Entry/Exit Position"] = algo_backtest["Position"].diff()

# Multiply share price by entry/exit positions and get the cumulatively sum
algo_backtest["Portfolio Holdings"] = (
    algo_backtest["ICF"] * algo_backtest["Entry/Exit Position"].cumsum()
)

# Subtract the initial capital by the portfolio holdings to get the amount of liquid cash in the portfolio
algo_backtest["Portfolio Cash"] = (
    initial_capital - (algo_backtest["ICF"] * algo_backtest["Entry/Exit Position"]).cumsum()
)

# Get the total portfolio value by adding the cash amount by the portfolio holdings (or investments)
algo_backtest["Portfolio Total"] = (
   algo_backtest["Portfolio Cash"] + algo_backtest["Portfolio Holdings"]
)

# Calculate the portfolio daily returns
algo_backtest["Portfolio Daily Returns"] = algo_backtest["Portfolio Total"].pct_change()

# Calculate the cumulative returns
algo_backtest["Portfolio Cumulative Returns"] = (
    1 + algo_backtest["Portfolio Daily Returns"]
).cumprod() - 1

# Print the DataFrame
algo_backtest.tail()

,ICF,Actual Returns,SMA Short,SMA Long,Signal,Algo Cumulative Returns,Entry/Exit,Position,Entry/Exit Position,Portfolio Holdings,Portfolio Cash,Portfolio Total,Portfolio Daily Returns,Portfolio Cumulative Returns
timestamp,,,,,,,,,,,,,,
2023-03-27 04:00:00+00:00,52.49,-0.002660,57.1836,56.7416,-1.0,0.579795,-2.0,-500.0,-1000.0,-52490.0,137473.3,84983.3,0.000000,-0.150167
2023-03-28 04:00:00+00:00,52.39,-0.001905,57.0618,56.6880,-1.0,0.580900,0.0,-500.0,0.0,-52390.0,137473.3,85083.3,0.001177,-0.149167
2023-03-29 04:00:00+00:00,53.61,0.023287,56.9618,56.6456,1.0,0.567372,2.0,500.0,1000.0,0.0,83863.3,83863.3,-0.014339,-0.161367
2023-03-30 04:00:00+00:00,54.28,0.012498,56.8946,56.6136,1.0,0.560281,0.0,500.0,0.0,0.0,83863.3,83863.3,0.000000,-0.161367
2023-03-31 04:00:00+00:00,55.54,0.023213,56.8568,56.5924,1.0,0.547276,0.0,500.0,0.0,0.0,83863.3,83863.3,0.000000,-0.161367

## Actual Portfolio Evaluation Metrics

In [37]:
# Create the list of the metric names
metrics1 = [
    'Annualized Return',
    'Cumulative Returns',
    'Annual Volatility',
    'Sharpe Ratio',
    'Sortino Ratio'
]

# Create a list that holds the column name
columns1 = ['Backtest']

# Initialize the DataFrame with index set to evaluation metrics and columns 
algo_evaluation_df = pd.DataFrame(index=metrics1, columns=columns1)

# Review the DataFrame
algo_evaluation_df

                   Backtest
Annualized Return       NaN
Cumulative Returns      NaN
Annual Volatility       NaN
Sharpe Ratio            NaN
Sortino Ratio           NaN

In [38]:
algo_evaluation_df.loc['Annualized Return'] = (
    algo_backtest['Portfolio Daily Returns'].mean() * 252
)

In [39]:
# Calculate the Cumulative returns metric
algo_evaluation_df.loc['Cumulative Returns'] = algo_backtest['Portfolio Cumulative Returns'][-1]

In [40]:
# Calculate the Annual volatility metric
algo_evaluation_df.loc['Annual Volatility'] = (
    algo_backtest['Portfolio Daily Returns'].std() * np.sqrt(252)
)

In [41]:
# Calculate the Sharpe ratio
algo_evaluation_df.loc['Sharpe Ratio'] = (
    algo_backtest['Portfolio Daily Returns'].mean() * 252) / (
    algo_backtest['Portfolio Daily Returns'].std() * np.sqrt(252)
)

In [42]:
# Calculate the Sortino ratio
# Start by calculating the downside return values

# Create a DataFrame that contains the Portfolio Daily Returns column
sortino_ratio_df = algo_backtest[['Portfolio Daily Returns']].copy()

# Create a column to hold downside return values
sortino_ratio_df.loc[:,'Downside Returns'] = 0

# Find Portfolio Daily Returns values less than 0, 
# square those values, and add them to the Downside Returns column
sortino_ratio_df.loc[sortino_ratio_df['Portfolio Daily Returns'] < 0, 
                     'Downside Returns'] = sortino_ratio_df['Portfolio Daily Returns']**2

# Calculate the annualized return value
annualized_return = sortino_ratio_df['Portfolio Daily Returns'].mean() * 252

# Calculate the annualized downside standard deviation value
downside_standard_deviation = np.sqrt(sortino_ratio_df['Downside Returns'].mean()) * np.sqrt(252)

# Divide the annualized return value by the downside standard deviation value
sortino_ratio = annualized_return/downside_standard_deviation

# Add the Sortino ratio to the evaluation DataFrame
algo_evaluation_df.loc['Sortino Ratio'] = sortino_ratio

In [43]:
# Review the portfolio evaluation DataFrame
algo_evaluation_df

                    Backtest
Annualized Return  -0.024631
Cumulative Returns -0.161367
Annual Volatility   0.178368
Sharpe Ratio        -0.13809
Sortino Ratio       -0.20284